[project]
name = "so-arm101-llm-integration"
version = "0.1.0"
dependencies = [
    "feetech-servo-sdk>=1.0.0",
    "ffmpeg>=1.4",
    "lerobot>=0.3.3",
    "pyserial>=3.5",
    "pyyaml>=6.0.2",
    "flask"
]